# Generated by Django 4.1.5 on 2023-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_data',
            field=models.DateTimeField(auto_now_add=True, help_text=' task end date'),
        ),
    ]
