# Generated by Django 4.1.5 on 2023-01-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_end_data_alter_task_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
