# Generated by Django 4.1.5 on 2023-01-20 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0027_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(default=8, help_text='order info', on_delete=django.db.models.deletion.CASCADE, to='shop_app.order'),
            preserve_default=False,
        ),
    ]
